# Generated by Django 3.1.7 on 2021-05-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equpie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('rent', models.IntegerField()),
                ('detail', models.CharField(max_length=150)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
