# Generated by Django 3.1.7 on 2021-06-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equpie', '0002_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
                ('product', models.CharField(max_length=20)),
                ('ndays', models.IntegerField()),
                ('retn', models.DateTimeField()),
            ],
        ),
    ]
