# Generated by Django 3.1.7 on 2021-06-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equpie', '0003_rent'),
    ]

    operations = [
        migrations.CreateModel(
            name='lrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod', models.CharField(max_length=20)),
                ('rentl', models.IntegerField()),
            ],
        ),
    ]
